### ISSUE TITLE
Make this a real library (instead of a submodule)

### ISSUE THREAD

**Issue by rfc2822** [bitfireAT/cert4android#13]
We would have to care less about compile-time settings when this would be a real library. It would be easier to integrate with other projects.

I think of this is a separate library that

- can be added as a normal dependency and then be used in other projects
- has two components, something like a `lib` and and `sample-app` directory:
  - `lib` contains the lib and is what is imported when other projects add the dependency
  - `sample-app` contains a minimum sample app that also allows to test cert4android in real when debugging (not imported with the dependency)

- [ ] make it a jitpack library
- [ ] document how to embed the library
- [ ] separate demo app from lib
  - [ ] build action for jitpack should only build lib
  - [ ] demo app can be opened in Android Studio to test and work on the lib

**Comment by ArnyminerZ** [comment]
I think the easiest approach would be to use something like [JitPack](https://jitpack.io/). It's the fastest way to deploy libraries. 

However, we can also upload them to MavenCentral, even though it is tougher, I think we would have more control on deployment. I've done this in the past, but I would have to come back and check what I did, since it's been a while.

If this is what we prefer over JitPack, I can take a look.

**Comment by ArnyminerZ** [comment]
According to [JitPack's documentation](https://jitpack.io/docs/ANDROID/) you must first configure the `maven-publish` plugin (there's a guide in [Android Developers](https://developer.android.com/build/publish-library)), I'll take a look and give further steps

**Comment by ArnyminerZ** [comment]
I've created a PR for this changes on #14, further instructions are there.
